global:
  domain: consul
  datacenter: dc2
  imageK8S: ndhanushkodi/consul-k8s-dev:peering34
  # image: ndhanushkodi/consul-dev:peering6
  image: ndhanushkodi/consul-dev:entpeering4
  enterpriseLicense:
    secretName: license
    secretKey: key
server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }

client:
  enabled: true
  grpc: true
  extraConfig: |
    {
      "log_level": "TRACE"
    }

ui:
  enabled: true

connectInject:
  enabled: true

controller:
  enabled: true
